//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_cdrBlob.h
//  Source: C:/cygwin/home/dds/OvernightTests/tmp_VVDLseE7qQ/build/etc/idl/dds_cdrBlob.idl
//  Generated: Wed Nov 28 12:53:07 2018
//  OpenSplice 6.9.181018OSS
//  
//******************************************************************
#ifndef _DDS_CDRBLOB_H_
#define _DDS_CDRBLOB_H_

#include "sacpp_mapping.h"
#include "cpp_dcps_if.h"


namespace DDS
{
   struct CDRSample;
   struct CDRBlob_uniq_ {};
   typedef DDS_DCPSUFLSeq < Octet, struct CDRBlob_uniq_> CDRBlob;
   typedef DDS_DCPSSequence_var < CDRBlob> CDRBlob_var;
   typedef DDS_DCPSSequence_out < CDRBlob> CDRBlob_out;

   struct OS_API CDRSample
   {
         CDRBlob blob;
   };

   typedef DDS_DCPSStruct_var < CDRSample> CDRSample_var;
   typedef DDS_DCPSStruct_out < CDRSample> CDRSample_out;
}




#endif
